# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'archive'
    configuration: 'release'
    sdk: 'iphoneos'
    scheme: 'OSCore'
    xcodeVersion: '12'
    packageApp: false
    destinationPlatformOption: 'iOS'
    args: '-archivePath $(system.defaultworkingdirectory)/archive/OSCore.framework-iphoneos.xcarchive  SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES'
- task: Xcode@5
  inputs:
    actions: 'archive'
    configuration: 'release'
    sdk: 'iphonesimulator'
    scheme: 'OSCore'
    xcodeVersion: '12'
    packageApp: false
    destinationPlatformOption: 'iOS'
    args: '-archivePath $(system.defaultworkingdirectory)/archive/OSCore.framework-iphonesimulator.xcarchive  SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(system.defaultworkingdirectory)/archive'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'xcodebuild -create-xcframework -framework ''$(system.defaultworkingdirectory)/archive/OSCore.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/OSHealthFitnessLib.framework'' -framework ''$(system.defaultworkingdirectory)/archive/OSCore.framework-iphoneos.xcarchive/Products/Library/Frameworks/OSHealthFitnessLib.framework'' -output ''$(system.defaultworkingdirectory)/archive/OSCore.xcframework'''
