# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build archive'
    configuration: 'release'
    sdk: 'iphoneos'
    scheme: 'OSCore'
    xcodeVersion: '12'
    packageApp: true
    destinationPlatformOption: 'iOS'
    args: 'SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES'
    archivePath: '$(system.defaultworkingdirectory)/archive'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls'
