# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'archive'
    sdk: 'iphoneos'
    xcodeVersion: '12'
    packageApp: false
    destinationPlatformOption: 'iOS'
- task: Xcode@5
  inputs:
    actions: 'archive'
    sdk: 'iphonesimulator'
    xcodeVersion: '12'
    packageApp: false
    destinationPlatformOption: 'iOS'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'xcodebuild -create-xcframework -framework ''./build/OSCore.framework-iphonesimulator.xcarchive/Products/Library/Frameworks/OSCore.framework'' -framework ''./build/OSCore.framework-iphoneos.xcarchive/Products/Library/Frameworks/OSCore.framework'' -output ''./build/OSCore.xcframework'''
